name: Create and Attach ZIP to Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history so we get all tags

      - name: Create ZIP file
        run: |
          # Get the tag name
          TAG_NAME=${GITHUB_REF#refs/tags/}
          
          # Create a custom zip file name
          ZIP_NAME="${GITHUB_REPOSITORY#*/}-$TAG_NAME.zip"
          
          # Create the zip file (excluding .git directory)
          zip -r "$ZIP_NAME" . -x "*.git*"
          
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload ZIP to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.ZIP_NAME }}
          asset_name: ${{ env.ZIP_NAME }}
          asset_content_type: application/zip
