name: Create Zip Archive on Release

on:
  release:
    types: [created]

# Add explicit permissions for the GITHUB_TOKEN
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Zip the repository
        run: |
          # Extract tag name without 'v' prefix if present
          ZIP_NAME="rtx-remix-custom-configs"
          
          zip -r "${ZIP_NAME}.zip" . -x "*.git*"
          
      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: rtx-remix-custom-configs-${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
